# Generated by Django 3.0.8 on 2020-08-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='prod',
        ),
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.ManyToManyField(to='Shop.SubCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='Shop.Tag'),
        ),
    ]
